const studentData = [
   {
    "STT": "1",
    "Họ đệm": "VÌ THỊ PHƯƠNG",
    "Tên": "DUNG",
    "Ngày sinh": "2010-04-05",
    "giới tính": "Nữ",
    "Dân tộc": "Thái",
    "Lớp": "10B1",
    "Học sinh trường": "Trường  PTDT Nội Trú THCS & THPT Sốp Cộp",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương.",
    " Môn học lựa chọn": "Vật lí, Hóa học, Sinh học, Tin học",
    "Chuyên đề lựa chọn": "Toán, Lý, Hóa"
  },
  {
    "STT": "2",
    "Họ đệm": "TÒNG NHẬT",
    "Tên": "DUY",
    "Ngày sinh": "29/07/2010",
    "giới tính": "Nam",
    "Dân tộc": "Thái",
    "Lớp": "10B9",
    "Học sinh trường": "Trường  PTDT Nội Trú THCS & THPT Sốp Cộp",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Vật lí, Hóa học, Công nghệ, Địa lý",
    "Chuyên đề lựa chọn": "Ngữ Văn, Địa lý, Công nghệ"
  },
  {
    "STT": "3",
    "Họ đệm": "LÒ LONG",
    "Tên": "NHẬT",
    "Ngày sinh": "30/03/2010",
    "giới tính": "Nam",
    "Dân tộc": "Thái",
    "Lớp": "10B7",
    "Học sinh trường": "Trường TH & THCS Sốp Cộp",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Ngữ Văn, Hóa học, Công nghệ"
  },
  {
    "STT": "4",
    "Họ đệm": "NGUYỄN MINH",
    "Tên": "QUÂN",
    "Ngày sinh": "01/01/2010",
    "giới tính": "Nam",
    "Dân tộc": "Kinh",
    "Lớp": "10B7",
    "Học sinh trường": "Trường TH & THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Ngữ Văn, Hóa học, Công nghệ"
  },
  {
    "STT": "5",
    "Họ đệm": "TÒNG THỊ THU",
    "Tên": "TRANG",
    "Ngày sinh": "16/09/2010",
    "giới tính": "Nữ",
    "Dân tộc": "Thái",
    "Lớp": "10B7",
    "Học sinh trường": "Trường PTDTBT THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Ngữ Văn, Hóa học, Công nghệ"
  },
  {
    "STT": "6",
    "Họ đệm": "LÒ THỊ ÁNH",
    "Tên": "DUNG",
    "Ngày sinh": "10/01/2010",
    "giới tính": "Nữ",
    "Dân tộc": "Thái",
    "Lớp": "10B8",
    "Học sinh trường": "Trường TH&THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Toán, Vật lý, Hóa học"
  },
  {
    "STT": "7",
    "Họ đệm": "VÌ THỊ",
    "Tên": "ĐIỂM",
    "Ngày sinh": "2010-09-08",
    "giới tính": "Nữ",
    "Dân tộc": "Thái",
    "Lớp": "10B8",
    "Học sinh trường": "Trường TH&THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Toán, Vật lý, Hóa học"
  },
  {
    "STT": "8",
    "Họ đệm": "LƯƠNG QUANG",
    "Tên": "ĐỨC",
    "Ngày sinh": "20/01/2010",
    "giới tính": "Nam",
    "Dân tộc": "Thái",
    "Lớp": "10B8",
    "Học sinh trường": "Trường TH&THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Toán, Vật lý, Hóa học"
  },
  {
    "STT": "9",
    "Họ đệm": "LƯỜNG THỊ MAI",
    "Tên": "HƯƠNG",
    "Ngày sinh": "23/07/2010",
    "giới tính": "Nữ",
    "Dân tộc": "Thái",
    "Lớp": "10B8",
    "Học sinh trường": "Trường TH&THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Toán, Vật lý, Hóa học"
  },
  {
    "STT": "10",
    "Họ đệm": "LÒ THỊ",
    "Tên": "HOÀI",
    "Ngày sinh": "05/01/2010",
    "giới tính": "Nữ",
    "Dân tộc": "Thái",
    "Lớp": "10B8",
    "Học sinh trường": "Trường TH&THCS Mường Lèo",
    "Môn học và hoạt động giáo dục bắt buộc": "Toán, Văn, Tiếng anh, Lịch sử, GDTC, GDQP-AN, Hoạt động TN-HN, GD lịch sử địa phương",
    " Môn học lựa chọn": " Hóa học, Địa lý, GD KTPL, Công nghệ",
    "Chuyên đề lựa chọn": "Toán, Vật lý, Hóa học"
  }
];